services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: "ponrove"
      CLICKHOUSE_PASSWORD: "321evornop"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    user: "${UID}:${GID}"
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
    profiles:
      - full
      - modular
      - integration
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 http://clickhouse:8123/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
