include:
  - openfeature-service.yaml
  - clickhouse.yaml
services:
  backend-server:
    build:
      context: ../
      dockerfile: ./build/docker/Dockerfile.server
    extends:
      file: extend-backend-env.yaml
      service: backend-environment
    ports:
      - 8080:8080
    depends_on:
      clickhouse:
        condition: service_healthy
    links:
      - openfeature-server
      - clickhouse
    profiles:
      - full
