include:
  - openfeature-service.yaml

services:
  backend-ingestion:
    build:
      context: ../
      dockerfile: ./build/docker/Dockerfile.ingestion
    extends:
      file: extend-backend-env.yaml
      service: backend-environment
    ports:
      - 8080:8080
    depends_on:
      - openfeature-server
    links:
      - openfeature-server
    profiles:
      - modular
  backend-hub:
    build:
      context: ../
      dockerfile: ./build/docker/Dockerfile.hub
    extends:
      file: extend-backend-env.yaml
      service: backend-environment
    ports:
      - 8081:8080
    depends_on:
      - openfeature-server
    links:
      - openfeature-server
    profiles:
      - modular
